### ISSUE TITLE
Unable to install using Composer

### ISSUE THREAD

**Issue by suraj-domandtom** [optimistdigital/nova-charcounted-fields#2] opened 2022-01-12 16:33 UTC
Using composer require elevate-digital/nova-charcounted-fields.

![image](https://user-images.githubusercontent.com/92387007/149182071-8af46104-6448-4bd0-a92a-34da88e5c932.png)

**Comment by KasparRosin** [comment] 2022-01-14 07:46
Hey! 

Was currently unable to reproduce this.
You can try if adding our github url into your repositories array in composer will help.

```
"repositories":[
    {
        "type": "vcs",
        "url": "git@github.com:optimistdigital/nova-charcounted-fields.git"
    }
]
```
------
In your case, for some reason, it's searching for the package from the wrong repository.
![image](https://user-images.githubusercontent.com/33309407/149470329-4139affb-4195-40ea-901b-d7b8d7dc5048.png)

**Comment by suraj-domandtom** [comment] 2022-01-14 09:52
Thanks. This is working for me.

I saw that help() function dont work.

**Comment by KasparRosin** [comment] 2022-01-18 08:49
Hey, @suraj-domandtom!

Could you open a separate issue regarding the help function.

Closing this one, since it's resolved. README was also updated.

**Closed as completed by KasparRosin** 2022-01-18 08:49 UTC
